# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Road to Max Stack
email: chennancd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Feature Technologies: Struts, Spring; SOAP, RESTful; ANT, Maven; Apache Httpd, Weblogic;
  PL/SQL, Oracle Database, MySql Database
baseurl: "" # the subpath of your site, e.g. /blog
url: "chennanni.github.io" # the base hostname & protocol for your site
github_username:  chennanni

# Build settings
markdown: kramdown

# Markdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge

theme: jekyll-theme-cayman